### ISSUE TITLE
Allow using tab key to terminate configuration list values

### ISSUE THREAD

**Issue by kayex** [adsa95/sirius-web#4]
When adding configuration values of the "list" type (for example, adding words to be censored to the _censor_ extension configuration), the user should be able to complete the current value and begin adding a new one with the `TAB` key. Currently the `Enter` key must be used, while the `TAB` key moves focus out of the input field entirely. Pressing `TAB` should move focus only when there are no incomplete chips remaining in the input field.

![screen shot 2017-03-06 at 15 42 28](https://cloud.githubusercontent.com/assets/1407203/23614533/89546f76-0283-11e7-9cc7-360d4266bd54.png)
_Here I would like to be able to press `TAB` to finish the word "fuck" and begin entering a new one. By pressing `TAB` immediately again, the focus should move to the next input field as expected._

This is how most applications behave — a good example is adding tags to sounds or playlists on Soundcloud.

Thoughts?

**Comment by adsa95** [comment]
This input is using the `md-chips` directive in Angular Material. I will try wrapping all inputs for each plugin in a `form` element and changing the `md-chip-append-delay` to see if it makes a difference, but otherwise I don't think it's worth the trouble to fix.

**Comment by adsa95** [comment]
After checking this myself, I think I misunderstood what part of your desired behavior is not currently implemented. `TAB` seems to change to the next input, but does not add the current input value to the array. If I understand the [documentation](https://material.angularjs.org/latest/api/directive/mdChips) correctly this should be easily fixed by adding the `TAB` keycode to the `md-separator-keys` attribute of the `md-chips` element.

**Comment by adsa95** [comment]
The web interface is now working as proposed in the initial comment. However, there is a small delay of 300ms from when the value is added and the input is refocused (and thus before you can change input using `TAB`), this is for accessibility reasons, for more information read the[ Angular Material documentation on md-chips](https://material.angularjs.org/latest/api/directive/mdChips#accessibility).

**Comment by kayex** [comment]
Awesome!
